pim_datagrid_load:
    path: /{alias}/load
    defaults: { _controller: pim_datagrid.controller.datagrid:loadAction }
    requirements:
        _method: GET
        _format: json

datagrid_loadmetadata:
    path: /{alias}/loadmetadata
    defaults: { _controller: pim_datagrid.controller.datagrid:loadMetaDataAction }
    options:
        expose: true
    requirements:
        _method: GET
        _format: json
